### ISSUE TITLE
yimmenu version link not found

### ISSUE THREAD

**Issue by Luh2Buzy** [SilentSal0/Silent-Night#10]
help 
![image](https://github.com/user-attachments/assets/a4cb49c0-649c-4c30-b0a0-57227f854396)

**Comment by Luh2Buzy** [comment]
also whats ur discord

**Comment by SilentSal0** [comment]
YimMenu version wasn't made by me. The person who made it removed his discord.
My discord is @silentsalo.
Link: https://discord.com/invite/UM6GhMQ9Ur
