### ISSUE TITLE
License Plate Text / Custom Plate - Outputting 00000000 Regardless of Desired Value

### ISSUE THREAD

**Issue by NRG0714** [SilentSal0/Silent-Night#10]
Changing license plate text on any vehicle outputs **00000000**

[Silent-Night Plate Changer Issue-Export_Attempt02.webm](https://github.com/user-attachments/assets/3f66ea0c-9845-47c4-b8af-8556b1e0b01b)

**Comment by SilentSalo** [comment]
Please, text me on discord, so I can send you *probably* fixed version, so you can test it. Discord: silentsalo.
