### ISSUE TITLE
Salvage Yard Options missing in yim version

### ISSUE THREAD

**Issue by nima1i** [SilentSal0/Silent-Night#11]
Hi, 
I've been using your script for quite some time in modest. Now that I switched to yim, I noticed some features are missing.
(Like being able to change vehicle type and robbery type).

I brought those features from the modest version and edited the code accordingly. But before I commit, I wanted to let you know and ask for permission.

Thanks for your great efforts.

**Comment by SilentSalo** [comment]
Text me on discord: silentsalo.
