### ISSUE TITLE
Update 1.70

### ISSUE THREAD

**Issue by veetomax** [SilentSal0/Silent-Night#12]
any updates for [Kiddion's] ?

I have tried updating the script
FMg     = 262145 
BTEg1   = 4538090 						-- bypass transaction error 1
BTEg2   = 4538091 						-- bypass transaction error 2
BTEg3   = 4538092 						-- bypass transaction error 3
GSIg    = 1667995 						-- get supplies instantly 

not working
NLCl     = 202 + 32 + 1 	-- night loop collect local [ Not sure what's wrong here ]!
night_loop_m_made [ The amount of money collected is not counted and the collection of funds has not been stopped ]

I really need this option : 
local function toggle_death_loop_afk()
	if localplayer ~= nil then
		while states.b28 do
			if death_loop_r_cash > 0 then
				if death_loop_m_count * 10000 >= death_loop_r_cash then
					states.b28 		  = false
					states.i59 		  = 0
					death_loop_r_cash = 0
					break
				end
			end
			death_loop_m_made  = death_loop_m_made + 5
			death_loop_m_count = death_loop_m_count + 5
			trigger_transaction(0x610F9AB4, 50000) [ i think error related : 0x610F9AB4 ]
			sleep(death_loop_delay)
		end
	end
end

**Comment by SilentSalo** [comment]
Hello. Kiddion's Modest Menu is outdated for already 3 months. You can't use it.

**Comment by veetomax** [comment]
still working for me using lua scripts only

**Comment by SilentSalo** [comment]
> still working for me using lua scripts only

Since the menu is discontinued, the script is discontinued either. If you read news on discord channel, all Silent Night versions are inactive at the moment.
