### ISSUE TITLE
Feature request - ability to change aircraft to a Pegasus vehicle

### ISSUE THREAD

**Issue by LintStalker** [SilentSal0/Silent-Night#13]
Hi,

Silent Night is an awesome script!

I was wondering if you could add the ability to change aircraft into Pegasus vehicles so that they can be taxied into a hanger so that it converts into a personal vehicle?  

Thanks!

**Comment by SilentSalo** [comment]
Hello. Silent Night is barely alive right now. I have a post on what is going on my Discord server. I'll update it to 1.70, but no new features. Sadly.

**Comment by Lochos97** [comment]
> Hello. Silent Night is barely alive right now. I have a post on what is going on my Discord server. I'll update it to 1.70, but no new features. Sadly.

Will it get updated for YimMenu also? Since YimMenu is still working, gettin updated frequently on github, i think you should prefer it over kiddions, even if most of them features work(on kiddions) but over time it will not be able to even launch. I know you update only kiddions, but imo it worths the shot. Also i just wanna say that the script is amazing, i had lots of fun and i hope it gets updated in the short future :D

**Comment by SilentSalo** [comment]
> > Hello. Silent Night is barely alive right now. I have a post on what is going on my Discord server. I'll update it to 1.70, but no new features. Sadly.
> 
> Will it get updated for YimMenu also? Since YimMenu is still working, gettin updated frequently on github, i think you should prefer it over kiddions, even if most of them features work(on kiddions) but over time it will not be able to even launch. I know you update only kiddions, but imo it worths the shot. Also i just wanna say that the script is amazing, i had lots of fun and i hope it gets updated in the short future :D

I'll update only the Cherax version. Both kiddion and yim's versions are discontinued.

**Comment by LintStalker** [comment]
Why are discounting Yimmenu?  It's still be updated.  There are several forked versions and all seem to run Silent Night without issue.

**Comment by SilentSalo** [comment]
Yim's version wasn't developed by me. I don't want to update something, that ain't honestly mine.

**Comment by LintStalker** [comment]
Ok, maybe whoever developed the version that works with Yimmenu will continue working on it?

**Comment by SilentSalo** [comment]
> Ok, maybe whoever developed the version that works with Yimmenu will continue working on it?

The original creator of Silent Night for Yim Menu left GTA community a lot of time ago. There was another developer for few versions, but then he left either.

I was maintaining Kiddion's and Cherax's versions only.
