### ISSUE TITLE
why dont this menu add spawning props or object related code?

### ISSUE THREAD

**Issue by lonelybud** [SilentSal0/Silent-Night#3]
this is not an issue.
Just wanted to ask why lot of kiddions lua scripts dont have such code like spawning object given its hash.
Is it bcz it is detected by anti cheat something or just people need time to code it.

**Comment by lonelybud** [comment]
again i am not requesting such feature. just asking a question. Thanks.

**Comment by SilentSal0** [comment]
Kiddion's Modest Menu is an external menu made by young enthusiast. It doesn't support calling natives or spawning objects. It doesn't have any API required for such options.

**Comment by lonelybud** [comment]
thanks.
