### ISSUE TITLE
Nightclub safe glitched

### ISSUE THREAD

**Issue by ghost** [SilentSal0/Silent-Night#4]
i was using the night loop safe (1 sec cooldown) from the script (kiddions menu) when suddenly the safe went over limit to 600k now it stuck like that because everytime i try to claim the money it says transaction invalid.
i tried logging on and off and restarting the game but that didn't help

**Comment by SilentSalo** [comment]
Try to complete some Nightclub missions. The safe should unstuck by itself with time.
