### ISSUE TITLE
Issue with "Cooldown Killer"

### ISSUE THREAD

**Issue by warlord1352** [SilentSal0/Silent-Night#4]
I was trying your awesome submenu and I think most things work but I tried doing the cooldown killer and gave error

![image](https://github.com/SilentSal0/Silent-Night/assets/15023912/23d4bf40-bb63-42f5-8e30-c10ca53ea93d)

**Comment by warlord1352** [comment]
I just took a look at it and is it just as simple as changing the value from "set_set" to "set_int"?

**Comment by SilentSal0** [comment]
Yeah, you're right bro. I know about that issue and it's fixed in recoded version that I'll release once I'm done with recoding.

**Comment by warlord1352** [comment]
No worries! I appreciate the quick reply though and keep the amazing work!

**Comment by SilentSal0** [comment]
Thanks.
