### ISSUE TITLE
Warehouse crates set price not works

### ISSUE THREAD

**Issue by Rexsell** [SilentSal0/Silent-Night#6]
Unfortunately, it is not clear how to use this function. I mean, im doing everything as said in hint in menu, but after instant complete mission rockstar throws transaction error, that prices have been changed, so transaction cannot be completed
I tried:
Set price in menu -> then enter warehouse -> laptop -> sell crates for 550mils -> leave warehouse -> instant complete -> error
enter warehouse -> set price in menu-> laptop -> sell crates for 550mils -> leave warehouse -> instant complete -> error
enter warehouse -> laptop -> sell crates for 1.8mil-> leave warehouse -> set price in menu -> instant complete -> error

How to fix?

**Comment by SilentSalo** [comment]
1. Special Cargo is currently highly detected. It's not recommended to use "Set Price" at all.
2. Max. transaction per sale is 6mil.
3. You always need to set the price first. After that you open your laptop and sell the crate for 6mil.
4. Always do sales while you're alone in session.

**Comment by Rexsell** [comment]
Uh, okay, understood, thank you
Will use smth else to get $
