### ISSUE TITLE
INSTA FINISH NOT WORKING

### ISSUE THREAD

**Issue by Muditcodes909** [SilentSal0/Silent-Night#8]
Hi I am using yim menu and your script from past 1 week till now it was perfect but from 2-3 days the insta finish just gives me the money not other players I tried everything updating the menu running as administrator turning of defender but still no change please help me

**Comment by SilentSalo** [comment]
Hello.

Instant Finish is just a function that requires a lot if things to be successful. First of all, it requires Script Host (not just Host of the heist). Moreover, Instant Finish requires all members of the heist to have really good Internet. Even more - you cannot Instant Finish The Pacific Job heist, it's just an Instant Finish limit. Finally, Instant Finish itself might be like that and you cannot do anything about it. That's how it works.
