### ISSUE TITLE
MC Wearhouse Fill and Bunker Fill

### ISSUE THREAD

**Issue by king69666** [SilentSal0/Silent-Night#9]
Hello. So I noticed that when using the MC Wearhouse Fill option, the warehouses don't actually fill. Only Mutt from the Acid Lab reply's saying that your supplies have arrived. The rest of the MC Businesses don't receive anything. 

To add to this, Bunker is inside of this option and at least from my perspective (haven't used it too much yet) it seems to empty out the Bunker supplies, I could be wrong though. May have just been that I used the Fast Produce button and didn't get a chance to actually see the supplies, OR, it's the same as the MC Wearhouse's and doesn't actually receive them. Not too sure why it's in this menu considering you have the Bunker in it's own menu as well. 

To note to that, the Bunker option that's alone by it's self works fine.

**Comment by king69666** [comment]
Also, special Cargo as well as Hanger Cargo work fine 🤷‍♂️

I also forgot to mention I'm using the latest pull for Yim.

**Comment by SilentSalo** [comment]
Hello.

I'm not supporting Yim version of my script, because I don't really like that menu. One guy from my discord supports and updates it. If you would like to speak to him, you can add me on discord: silentsalo.
